### ISSUE TITLE
Consider renaming bits of ipsr and icvec

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#105]
Since the document usually abbreviates *command queue* as *CQ*, and similarly for the other queues, consider:
 - renaming bits `cip`, `fip`, and `pip` in register `ipsr` as `cqip`, `fqip`, and `pqip`;
 - renaming bits `civ`, `fiv`, and `piv` in register `icvec` as `cqiv`, `fqiv`, and `pqiv`.

If it were up to me, I'd also rename `cqcsr` bit `cie` to `cqie`; `fqcsr` bit `fie` to `fqie`; and `pqcsr` bit `pie` to `pqie`.

**Comment by ved-rivos** [comment]
Discussed in IOMMU TG and agreed to retain the current names.
