### ISSUE TITLE
Consider adjusting encoding of fault record TTYP field

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#106]
This is not proposed as a requirement, but the Architecture Review Committee believes it would be more in the spirit of RISC-V design if fault record TTYP fields were encoded so that *untranslated* and *translated* types differed in value by a single bit.  One simple way to achieve this would be simply to shift some of the encodings as follows:

| TTYP  | Meaning                                   |
| ----- | ----------------------------------------- |
| 0     | None                                      |
| 1     | Untranslated read for execute transaction |
| 2     | Untranslated read transaction             |
| 3     | Untranslated write/AMO transaction        |   
| 4     | *reserved*                                |
| 5     | Translated read for execute transaction   |
| 6     | Translated read transaction               |
| 7     | Translated write/AMO transaction          |   
| 8     | PCIe ATS Translation Request              |
| 9     | PCIe Message Request                      |

This also maximizes commonality of encoding for the PCIe-specific types.

**Comment by ved-rivos** [comment]
PR #110 to address this issue.
