### ISSUE TITLE
Consider reordering DCs and PCs for greater consistency

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#11]
The in-memory data structures for device contexts (DCs) and process contexts (PCs) could be made a little more consistent by reordering the doublewords so that the `ta` (translation attributes) and `fsc` (first-stage context) doublewords are always first and second, with bit 0 of the `ta` doubleword always containing the V (valid) bit for the structure.

As currently specified, a DC's V bit is in doubleword `tc` (translation control), but a PC's V bit is in doubleword `ta` (translation attributes).  Even more unexpected, the PC's V bit is not in the first doubleword but in the second doubleword, deviating from all other similar structures.

Because only the `ta` and `fsc` doublewords are common to both DCs and PCs, it seems logical to me that one of these two doublewords should be first so it can consistently contain the V bit for the respective structure in bit 0.  In fact, I can see no reason why both `ta` and `fsc` shouldn't consistently be the first two doublewords for all DCs and PCs.

(It also appears to me that the bits currently defined for the `tc` doubleword could all be consolidated into the `ta` doubleword if it becomes the first, which would then probably argue for making the whole `tc` doubleword simply reserved or custom and perhaps also changing the name of `ta` to something else.  But I'll leave those choices to the IOMMU task group.)

**Comment by ved-rivos** [comment]
Reviewed in IOMMU TG on 8/11/2022.
PR https://github.com/riscv-non-isa/riscv-iommu/pull/15 created to align the valid bit for PC and DC.
The IOMMU TG discussed suggestion to merge tc and ta and agreed not to make the change as tc
hold global device level translation controls whereas ta hold per process attributes that affect first stage
tranlations.
