### ISSUE TITLE
How is the width of an iohpmevt register defined?

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#121]
Section 5.23, "Performance-monitoring event selector", says
> When `capabilities.HPM` is set, the `iohpmcycles` and the `iohpmevt1` register must be present and be at least 32-bits wide.

What does it mean for an `iohpmevt` register to be *N* bits wide, *N* < 64?

**Comment by ved-rivos** [comment]
It should read `iohpmctr1`. I also see that this statement is repeated twice - second time with the typo.

**Comment by ved-rivos** [comment]
PR #125
