### ISSUE TITLE
Reset footprint can be reduced

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#123]
In Section 5.2, "Reset behavior", it is not necessary for reset to zero all of registers `cqcsr`, `fqcsr`, and `pqcsr`.

In `cqcsr`, only bits `cqen`, `cie`, `cqon`, and `busy` need to be zeroed on reset.

In `fqcsr`, only bits `fqen`, `fie`, `fqon`, and `busy` need to be zeroed on reset.

In `pqcsr`, only bits `pqen`, `pie`, `pqon`, and `busy` need to be zeroed on reset.

**Comment by ved-rivos** [comment]
This was done to actually minimize the reset foot print. Reset of the error bits (8 bits) avoided needing to specify a reset of the larger MSI configuration table state. The MSI configuration table may have X after a reset if the error bits are not reset they may lead to a memory write being trigger to unknown/unexpected memory locations.

**Comment by ved-rivos** [comment]
We could constrain software including random tests to not enable interrupts. 
`fctl` can also be removed from the list.
PR #129

**Comment by jhauser-us** [comment]
> if the error bits are not reset they may lead to a memory write being trigger to unknown/unexpected memory locations.

How is that possible if `cqcsr.cie`, `fqcsr.fie`, and `pqcsr.pie` are all set to zeros on reset?  (See again my list above.)

**Comment by jhauser-us** [comment]
See also #137.
