### ISSUE TITLE
Allow unneeded bits of msi_data_* registers to be zeros

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#131]
I see that an IOMMU's MSI configuration table (Section 5.28) has the same form as an MSI-X Table for PCI.  I see also that an MSI address in the table is specified as WARL.  However, for MSI data it appears a RISC-V IOMMU is required to support a full 32-bit value.

I don't object to allowing an IOMMU implementation to support 32 bits for MSI data if it wants.  But if we can assume that in some RISC-V systems the reasonable destinations for MSIs are only standard IMSICs and/or APLICs as defined by the current RISC-V Advanced Interrupt Architecture (AIA), no custom components, then it is known that such a system has no use for more than 11 bits of MSI data (and possibly fewer bits, depending on how many minor interrupt identities are supported by the IMSICs and APLICs in the system).

The IOMMU spec should allow a system to implement only the number of bits for MSI data that are needed.

**Comment by ved-rivos** [comment]
PR #134
