### ISSUE TITLE
For MSI PTEs, "translate-R/W mode" is now "basic translate mode"

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#132]
In the Advanced Interrupt Architecture, the mode for MSI PTEs that was for a time called *translate-R/W mode* (and other names earlier) is now known as *basic translate mode*.

(Hopefully, this newest name is both anodyne and descriptive enough to survive.)

**Comment by ved-rivos** [comment]
PR #133
