### ISSUE TITLE
Should msiptp.MODE be required to be Bare when iohgatp.MODE is Bare?

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#141]
In the algorithm of Section 2.3, "Process to translate an IOVA", if `iohgatp.MODE` is Bare then any MSI page table is ignored.  (In step 17, if `iohgatp.MODE` is Bare then the address is translated by the Privileged ISA's single-stage translation algorithm, and if there's no fault, translation is complete, ignoring any MSI page table.)

Should this combination be listed in Section 2.1.4, "Device-context configuration checks", as causing a DC to be considered misconfigured?:  `capabilities.MSI_FLAT` is 1, `iohgatp.MODE` is Bare, and `msiptp.MODE` is not Bare.

**Comment by ved-rivos** [comment]
It was not added to the check as it was benign for hardware. When no GPA are produced then the MSI PTs do not apply.
