### ISSUE TITLE
Clarify permissions for MSI PTEs

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#143]
An MSI page table entry (MSI PTE) permits read and write accesses but not execute.  The allowed permissions are thus equivalent to a regular RISC-V PTE with R = W = U = 1 and X = 0.

**Comment by ved-rivos** [comment]
I see the MSI PTE specification says the U should be treated differently but not how. Will add a clarification about this.

**Comment by ved-rivos** [comment]
PR #149
