### ISSUE TITLE
Write to memory by IOFENCE.C must occur only after command completes

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#146]
Section 3.1.2, "IOMMU Command-queue Fence commands", says
> If AV=1, the IOMMU writes DATA to memory at a 4-byte aligned address `ADDR[63:2] * 4` as a 4-byte store.

It forgets to say that this memory write occurs only after completion of the `IOFENCE.C` command.

**Comment by ved-rivos** [comment]
PR #147
