### ISSUE TITLE
Single-copy atomic accesses

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv-non-isa/riscv-iommu#153]
> The size of a single-copy atomic memory access implemented by the IOMMU is `UNSPECIFIED` but is required to be at least 32-bits when the harts in the system implement RV32 and is required to be 64-bits when the harts in the system implement RV64.

Considering heterogeneous systems, should this say that it's at least 32-bits when **all** of the harts are RV32 and at least 64-bits when **any** of the harts is RV64?

**Comment by ved-rivos** [comment]
PR #157
