### ISSUE TITLE
capabilities.PAS

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv-non-isa/riscv-iommu#162]
capabilities.PAS is defined as "Physical Address Size (value between 32 and 56)" but I think that you can have <32-bits of PA on RV32 (or even RV64).  Maybe systems with IOMMUs will generally not have small PA spaces but it's theoretically possible and I don't see a need to place a lower limit on it.

**Comment by ved-rivos** [comment]
No reason to place a lower or upper limit. PR #163
