### ISSUE TITLE
Queue initialization neglects to zero cqt, fqh, pqh

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#172]
Section 6.2, "Guidelines for initialization", hasn't yet been fully updated for changes elsewhere:

- The steps for initializing the command queue neglect to zero `cqt`.

- The steps for initializing the fault queue neglect to zero `fqh`.

- The steps for initializing the page-request queue neglect to zero `pqh`.

**Comment by ved-rivos** [comment]
This is queued in PR #161
