### ISSUE TITLE
Should "redirection of interrupts" be supported without G-stage translation?

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#177]
Section 1.2.1, "Non-virtualized OS", lists among the expected usage models, "Dynamic redirection of interrupts".  Should this use be supportable by an MSI page table without also requiring G-stage address translation to be active?

Currently, in the algorithm of Section 2.3, "Process to translate an IOVA", in Step 17, "If a G-stage page table is not active in the device-context", then all of Steps 18 through 20 are skipped, including Step 19 for identifying and handling accesses to MSI pages.  There's really no reason why the provision of MSI PTs and G-stage PTs can't be independent of one another (so long as MSI translations continue to take precedence over G-stage translations).

**Comment by ved-rivos** [comment]
This use can be achieved without use of G-stage address translation by just use of S-stage PT to remap the interrupt file address. However, this bullet item may want to be removed as it is much less useful to do that.
