### ISSUE TITLE
MSI conversion occurs even if 2nd-stage translation is Bare

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#192]
Currently, in Section 2.3, "Process to translate an IOVA", if second-stage address translation is Bare (step 17), then MSI conversions (step 19) is bypassed.  The Architecture Review Committee has concluded this is an error; MSI conversion should always occur if enabled (not Off).

The easiest fix is presumably to delete the current step 17 and remove this condition from the start of the next step (currently 18, before renumbering):  "If second-stage address translation is not Bare then".

**Comment by ved-rivos** [comment]
A device being associated with a guest with second-stage set to Bare does not provide DMA protection to the host memory space (or other guests) and the address space of guest cannot be virtualized. If such a guest had its guest interrupt files moved then without a G-stage being active it would need cooperation of the guest as the guest needs to now use different addresses to generate IPIs. So such a configuration is likely used with devices associated with the host or in case of a non-virtualized OS. For a host, the redirection of MSI is not always possible as the MSI address translation only supports translating addresses but not the identities. Without ability to also map identities the interrupt identities will need to be globally allocated across all harts. The maximum number of identities supported by a hart is small - 2K. Supporting this however is not an issue - PR #193 created to support this mode.
