### ISSUE TITLE
Encoding of TTYP field in Fault-queue records

### ISSUE THREAD

**Issue by malejo97** [riscv-non-isa/riscv-iommu#202]
Hello!

Think i found a minor issue when implementing the encoding of TTYP field in Fault-queue records:
TTYP is 6-bit wide but is encoded in _Table 12: Fault record TTYP field encodings_ up to a value of 31.

I propose for example designating bits **10-31** as _reserved_ and bits **32-63** for _custom use_.

**Comment by ved-rivos** [comment]
Agree with the proposal. Addressed in PR #203
