### ISSUE TITLE
PC.fsc definition refers to DC.fsc

### ISSUE THREAD

**Issue by snelson2-intel** [riscv-non-isa/riscv-iommu#208]
Prior to figure 27, IOMMU text says: 
"If PDTV is 0, the fsc field in DC holds the iosatp that provide the controls for first-stage address translation and protection."  

I think this text should be :
"If PDTV is 1, the fsc field in PC holds the iosatp that provide the controls for first-stage address translation and protection."

On a related note, figure 27 should define iosatp when PDTV is 1 (it says 0).  Presently this figure is a duplicate of figure 18 in the device context section.  Since the iosatp definition is the same whether PDTV is 0 or 1, I suggest changing the names of both figures to "IO Supervisor address translation and protection (iosatp) field" removing "when PDTV is 0/1"

**Comment by ved-rivos** [comment]
PR #209 created to address this.

**Comment by snelson2-intel** [comment]
Perhaps "If PDTV is 1" isn't necessary at all, because I think that if PDTV is 0 then the process directory does not exist.

**Comment by snelson2-intel** [comment]
Also there's no note about substituting iovsatp for iosatp in the fsc field.  I think this ought to be analogous to the RISC-V priveledged ISA specification which calls out alternative definitions for the vsatp and satp registers.
