### ISSUE TITLE
iohgatp layout comes late in data structure section

### ISSUE THREAD

**Issue by snelson2-intel** [riscv-non-isa/riscv-iommu#212]
Most of the data structure definition section begin with a figure showing the layout of bit fields (i.e. 2.1.3.tc, 2.1.3.ta, 2.1.3.fsc).  This figure provides context for the subsequent field descriptions.

In 2.1.3.iohgatp, the field descriptions preceed the figure.  I think figure 16 should be moved to the start of the section to improve readability.
In 2.1.3.msi_addr_mask / msi_addr_pattern, the field descriptions preceed the figure.  I think figures 21 and 22 should be moved to the start of the section to improve readability.

**Comment by ved-rivos** [comment]
PR #213 reorders the diagrams.
