### ISSUE TITLE
Chapter 1 Typos

### ISSUE THREAD

**Issue by jscheid-ventana** [riscv-non-isa/riscv-iommu#226]
1.0-rc3

> The first-stage translate the VA to a SPA and enforces the configured memory protections.

"translates".

> If the virtual memory scheme selected for neither stages is Bare then the IOVA is a VA.

"neither stage".

> Such a configuration would be typically be employed

"would be typically employed".

> when the device control is passed-through

"passed through".

> to identify a collection of process identifier that share

"identifiers"

> Device contexts programmed with same GSCID

"with the same"

> The supported device_id width may be up to 24-bit.

"24 bits."

> The supported process_id may be up to 20-bit.

"20 bits."

**Comment by ved-rivos** [comment]
PR #227 created to address.
