### ISSUE TITLE
process_context_t double-word ordering

### ISSUE THREAD

**Issue by sometimesawake** [riscv-non-isa/riscv-iommu#250]
[typedef struct {
    pc_fsc_t   fsc;
    pc_ta_t ta;
} process_context_t;](https://github.com/riscv-non-isa/riscv-iommu/blob/main/iommu_ref_model/libiommu/include/iommu_data_structures.h#L373)

Hi Ved, could you check if this ordering is correct.
The double-word ordering seems to be different than the device_context.

**Comment by ved-rivos** [comment]
Don - thanks. Yes, the order should be reversed - fixed in PR #251
