### ISSUE TITLE
How to invalidate the MSI page table cache？Are the two addresses A in Figure 1 and Figure 2 the same?

### ISSUE THREAD

**Issue by 18772820305** [riscv-non-isa/riscv-iommu#278]
1.
![689307860d523b2831ec40fd6d61b425](https://github.com/riscv-non-isa/riscv-iommu/assets/49462543/0f09c1f9-a888-46dc-8dbf-f3dfb2be2950)

2.
![45d0093ea5625096f4c5a8aef303b533](https://github.com/riscv-non-isa/riscv-iommu/assets/49462543/a663af1a-a868-4bf8-9201-0d6959b30d47)

**Comment by runninglinuxkernel** [comment]
The instructions of invalid MSI page table have provided at chapter 6.3.3.
I think the address A in those two places are the same, GPA. 
MSI page table doing the address translation of Guest interrupt file from GPA  to SPA.

**Comment by ved-rivos** [comment]
@18772820305 please let me know if there are further questions.

**Comment by 18772820305** [comment]
Can the ADDR operand of IOTINVAL.GVMA command be a GVA?

**Comment by ved-rivos** [comment]
Please see Table 10 row 3

**Comment by ved-rivos** [comment]
Closing this issue. Hope that addressed the question. Please feel free to ask if there are further questions.
