### ISSUE TITLE
remove "PDT" word

### ISSUE THREAD

**Issue by runninglinuxkernel** [riscv-non-isa/riscv-iommu#279]
In chapter 3.1.1,

IOMMU operations cause implicit reads to PDT, first-stage and second-stage page tables. To reduce
latency of such reads, the IOMMU may cache entries from the first-stage and/or second-stage page
tables in the IOMMU-address-translation-cache (IOATC).

This chapter just talk about invalidate the S1 and S2 page table cache, so for the first sentence, should we remove the word "PDT" avoid confusing?

**Comment by ved-rivos** [comment]
The paragraph discusses the implicit reads to PDT to draw attention explicitly to the fact that when second-stage is not Bare, the `PPN`s held in the non-leaf PDT entries and in the `pdtp` are guest PPNs. They are translated by the second-stage page table to determine the SPA to access the non-leaf PDT entries and the `PC`. This process could lead to the second-stage address-translation caches being updated.

**Comment by runninglinuxkernel** [comment]
yes, your explanation is much better the first sentence of chapter 3.1.1 which is confusing me or other readers.

**Comment by ved-rivos** [comment]
This has been explained in detail before - e.g. section 2.3.2,

**Comment by runninglinuxkernel** [comment]
Thanks a lot!
