### ISSUE TITLE
Sorry,how to configure the value of capabilities.PAS?

### ISSUE THREAD

**Issue by augsug** [riscv-non-isa/riscv-iommu#284]
PAS is a 6-bits field in capabilities,which means Physical Address Size supported by the IOMMU.But how can i configure this filed?

![WXWorkLocal_20240313101734](https://github.com/riscv-non-isa/riscv-iommu/assets/54934334/c82a8f5f-96b8-4a1d-af9b-5efe001d788d)

**Comment by ved-rivos** [comment]
The `capabilities` register is used to report the capabilities of the IOMMU hardware. This is a read-only register used for enumeration and is not a configuration register. So the `PAS` (and other hardware capabilities) are not software configurable. Some hardware implementations, such as soft-IPs, may have build time configurations for the hardware and may also support mechanisms like straps/fuses to configure the hardware  at implementation time.

**Comment by ved-rivos** [comment]
I hope that addressed the question. Please feel free to ask if there are further questions.

**Comment by augsug** [comment]
I got u.  if i set this field in 6'b0000_01，what does this mean?Physical Address Size is 4KiB or something ? 
look forward to your advice:)

**Comment by ved-rivos** [comment]
@augsug - a value of 6'b0000_01 implies 1-bit and a value of 6'b1110_00 implies 56-bit.

**Comment by viktoryou** [comment]
Seems that a value of 0 would be meaningless or unspecified, right?
