### ISSUE TITLE
Question about VA fault detection in system both support Sv32 and Sv39

### ISSUE THREAD

**Issue by viktoryou** [riscv-non-isa/riscv-iommu#285]
In such IOMMU implementation with capabilities.Sv32=1 & capabilities.Sv39=1 and 64-bit addresss width, as the IOMMU model suggests, when iosatp.MODE=Sv32 and DC.SXL=1, 63–32 should all equal to bit 31, or else a page-fault exception will occur.

While I think this is not exactly what the IOMMU spec requires:
> When SXL is 1, the following rules apply:
> * If the first-stage is not Bare, then a page fault corresponding to the original access type occurs if
the IOVA has bits beyond bit 31 set to 1.
> * If the second-stage is not Bare, then a guest page fault corresponding to the original access type
occurs if the incoming GPA has bits beyond bit 33 set to 1.

I prefer this is a bug in the model (see [code](https://github.com/riscv-non-isa/riscv-iommu/blob/main/iommu_ref_model/libiommu/src/iommu_two_stage_trans.c#L102)), since in a 32-bit system, there is no such canonical rule for Sv32 as Sv39/Sv48/Sv57 in 64-bit system. The check may only detect the [63:32] for IOVA and [63:34] not to one.

**Comment by ved-rivos** [comment]
You are right that the code would produce a wrong result for `0xFFFFFFFF_????????` case for SXL=1. Fixing as follows:
```
if ( (masked_upper_bits != 0 && masked_upper_bits != mask && SXL == 0) ||
     (masked_upper_bits != 0 && SXL == 1) ) goto page_fault;

```
