### ISSUE TITLE
Question about pqen change to set pqh

### ISSUE THREAD

**Issue by viktoryou** [riscv-non-isa/riscv-iommu#295]
In the chapter 5.17 of the Spec, 
> Changing pqen from 0 to 1, sets the pqh register and the pqcsr bits pqmf and pqof to 0.

From my understanding , the pqh should be replaced with pqt (from hardware's view). Please help to check.

**Comment by ved-rivos** [comment]
You are right. It is a typo and pqh should be pqt. Update queued in https://github.com/riscv-non-isa/riscv-iommu/pull/243/commits/08686fbb72b000ca9d8b8fcaaa252739244b382b
