### ISSUE TITLE
Performance-monitoring capability and registers

### ISSUE THREAD

**Issue by dgptha** [riscv-non-isa/riscv-iommu#3]
The descriptions of the performance-monitoring registers refer to a HPM field in the capabilities register (e.g. in Section 4.21), which the capabilities register doesn't have. The capabilities register has a field named PMON. We should use one or the other, but not both. Changing to PMON might require a fair bit of modifications.

**Comment by pperesse** [comment]
Yes, we should keep HPM (Hardware Performance Monitor) everywhere.

**Comment by pperesse** [comment]
I agree. thanks

**Comment by dgptha** [comment]
Addressed with pull request #7

**Comment by ved-rivos** [comment]
Thanks for the PR. I have merged it in. Resolving as completed.
