### ISSUE TITLE
Question related to Bypass/Global bits in ATS_TRANS_RESP

### ISSUE THREAD

**Issue by zetalog** [riscv-non-isa/riscv-iommu#309]
Our verification guys noticed a difference between the refence model and the model they developed based on SPEC:

```
        // only use Untranslated requests to access the implied 4 KiB memory range
        ...
        rsp_msg->trsp.Global = vs_pte.G;
        ...
```

ATS response uses VS PTE.G which doesn't reflect to the statements of the DTI specification of **5.2.2 DTI_ATS_TRANS_RESP**.

### Bypass

In the new revision of the DTI specification (edition 3, issue E.b), there is no Global bit defined, but defined Bypass bit:

**BYPASS, bit [17]** 

This field indicates that translation for this StreamID is bypassed.
 _0 Normal translation
 1 Translation bypassed_
When the value of this field is 1, the VA and the PA of the translation are the same. This bit must be 0 if the value of IA in the translation request is greater than the range shown in the OAS field of the DTI_ATS_CONDIS_ACK message that was received during the connection sequence.

### Global

In the old DTI version (edition 3, early release), it forces setting Global to 1 when Bypass is 1 and SSV is 1.

**Global, bit[72]**

This bit indicates whether this translation appplies to all SubstreamIDs
 _0 - Non-global.
 1 - Global._
When the value of the SSV bit in the requesting DTI_ATS_TRANS_REQ message is 0, this bit is reserved, SBZ.
When the value of the SSV bit in the requesting DTI_ATS_TRANS_REQ message is 1, and the value of BYPASS is 1, this bit must be 1.

Now we are wiring these bits to 0s both in our design and the verification model which matches the behavior of our PCIe IPs.

Is this a compatibility issue in the reference model?

**Comment by ved-rivos** [comment]
Mapping to protocols such as DTI should follow the rules provided by those specifications. The IOMMU specification follows the PCIe specification and any such mapping to DTI/LTI or other implementations is implementation defined.

**Comment by zetalog** [comment]
Sorry, my mistake.
This is the one from the recent DTI specification:

![image](https://github.com/riscv-non-isa/riscv-iommu/assets/3615765/360ffd61-4b2d-4a72-b335-956b70ba9854)

**Comment by ved-rivos** [comment]
The previous picture you posted is for DTI TBU. As noted above, the mapping to implementation specific buses like DTI is implementation specific.

**Comment by zetalog** [comment]
From PCIe 5.0, there is no Bypass field in CPL:

And can see Global bit in Table 10-3:

```
Global Mapping - If this bit is Set, the ATC is permitted to cache this mapping entry in all PASIDs. If Clear, the ATC is
permitted to cache this mapping entry only in the PASID associated with the requesting PASID. This bit may only be Set
if the associated Translation Request had a PASID TLP Prefix.
```

**Comment by ved-rivos** [comment]
> From PCIe 5.0, there is no Bypass field in CPL:

Bypass is a DTI concept and as you noted not a PCIe concept.

**Comment by zetalog** [comment]
According to our PCIe guys, PCIe IPs containing "Global" bit follow DTI 2.0 and early DTI 3.0 spec.

**Comment by ved-rivos** [comment]
Please check if you see any reference to DTI in PCIe specification.

**Comment by zetalog** [comment]
> The previous picture you posted is for DTI TBU. As noted above, the mapping to implementation specific buses like DTI is implementation specific.

Shall the implementation dependency be mentione for this paragraph?

**2.6. PCIe ATS translation request handling**

• _Global field is set to the value determined from the first-stage page tables if translation could be successfully completed and the request had a PASID present_. In all other cases, including MSI address translations, this field is set to 0.

**Comment by zetalog** [comment]
> Please check if you see any reference to DTI in PCIe specification.

There is no reference of DTI can be found in PCIe spec, just can see reference of DTI in the IP data book.

**Comment by ved-rivos** [comment]
Such an IP using DTI always receives Global as 0.  It is equivalent to such an IP ignoring the Global bit - which is allowed by PCIe - this only results in multiple translations being requested for the same Untranslated Address under different PASIDs - see 10.2.3.8.

**Comment by zetalog** [comment]
> Such an IP using DTI always receives Global as 0. It is equivalent to such an IP ignoring the Global bit - which is allowed by PCIe - this only results in multiple translations being requested for the same Untranslated Address under different PASIDs - see 10.2.3.8.

Is that means if an implementation doesn't support ATS.INVAL G field, it can choose to respond G=0 to ATS translation request?

**Comment by ved-rivos** [comment]
Firstly, I would like to request you to not reproduce information from the PCIe specification that is licensed to you in this GitHub. If you need to refer to a section then providing a section number is sufficient. Would want to avoid any copyright, compliance, antitrust, etc. issues. An implementation that always responds to endpoint with the G bit set to 0 may not run into issues.

**Comment by zetalog** [comment]
> Firstly, I would like to request you to not reproduce information from the PCIe specification that is licensed to you in this GitHub. If you need to refer to a section then providing a section number is sufficient. Would want to avoid any copyright, compliance, antitrust, etc. issues. An implementation that always responds to endpoint with the G bit set to 0 may not run into issues.

Sure, just sorted all of them out. Thanks for the reminds.

> The previous picture you posted is for DTI TBU. As noted above, the mapping to implementation specific buses like DTI is implementation specific.

My question is still about the specification/reference model clarification.
From the RISCV IOMMU specification, we cannot infer ATS handler are allowed to respond G=0, while PCIe spec permits.

**Comment by ved-rivos** [comment]
The PCIe specification permits ignoring the response from the IOMMU. The RISC-V IOMMU specification is compliant with the PCIe specification and no further note is required.

**Comment by zetalog** [comment]
OK, thanks, marking it closed.

**Comment by space-mit** [comment]
One more thing I'd like to mention is:

For an implementation that is based on DTI. "Bypass" is a necessary field for ATS response, it combines with "Range" field. Upon accepting such an translation response, the DMA master side (e.x., PCIe RC) DTI bridge is responsible for generating "output address" using "input address" and "range", "bypass" fields, with lower bits indicated by "bypass/range" coming from the "input address" in translation request and higher bits coming from "output address" in translation response.

As such, "Bypass" is also used in ATS translations.

However, the current reference model seems like a TLP base model, cares less about DTI ATS interfacing.
Probably should move all of those ATS bridge side stuffs to implementation specific or test bench specific, and not be a part of IOMMU model.

**Comment by zetalog** [comment]
One more thing I'd like to mention is:

For an implementation that is based on DTI. "Bypass" is a necessary field for ATS response, it combines with "Range" field. Upon accepting such an translation response, the DMA master side (e.x., PCIe RC) DTI bridge is responsible for generating "output address" using "input address" and "range", "bypass" fields, with lower bits indicated by "bypass/range" coming from the "input address" in translation request and higher bits coming from "output address" in translation response.

As such, "Bypass" is also used in ATS translations.

However, the current reference model seems like a TLP base model, cares less about DTI ATS interfacing.
Probably should move all of those ATS bridge side stuffs to implementation specific or test bench specific, and not be a part of IOMMU model.
