### ISSUE TITLE
Question about internal data path error definition and usage

### ISSUE THREAD

**Issue by viktoryou** [riscv-non-isa/riscv-iommu#317]
From the spec, I could not find the exact explanation of internal data path error and what would be the cause of it, neither is the model. Below is an indirect description.
> The cause (272, internal data path error) is still reported if DTF is 1(I translated it from table 11). Setting DTF to 1 does not disable error responses from being generated to the device in response to faulting transactions. Setting DTF to 1 does not disable reporting of faults from the IOMMU that are not related to the address translation process.(chapter 2.1.3)

It seems like internal data path error may belong to one of the above type. But I still have no idea what does it refer to. I guess internal data path error should not be a broad definition and a precise explanation should be added.

Could you help to check that?

**Comment by ved-rivos** [comment]
Some IOMMUs may implement RAS features such as parity or ECC protection on memories and internal buses. Detection of uncorrectable errors in these internal data paths leads to internal data  path error. Much of this is microarchitectural and cannot be precisely defined. There is discussion on this topic in section 7.4.
