### ISSUE TITLE
Is it reasonable for ATS Invalidate Completion to check its RID width and report an fault if it is wider than that supported by the IOMMU mode？

### ISSUE THREAD

**Issue by wangyongzhen0322** [riscv-non-isa/riscv-iommu#333]
There is no related check in the c_model. And if the fault is reported , will it be useful?

**Comment by ved-rivos** [comment]
If an IOMMU receives a invalidation completion where the combination of RID and iTAG does not match an outstanding invalidation then such messages are ignored. An IOMMU cannot receive a RID wider than its maximum supported width as these messages are received over a hardware bus from the root port.
