### ISSUE TITLE
Question about stop marker detect in model when sending prgr 

### ISSUE THREAD

**Issue by viktoryou** [riscv-non-isa/riscv-iommu#337]
From the spec,
> "Page request" messages that require a response, i.e. those with "Last Request in PRG" field set to 1 and are not "Stop Marker" messages, may be auto-completed by an IOMMU generated “Page Request Group Response” message as specified in Section 2.7.

In the model, see the [code](https://github.com/riscv-non-isa/riscv-iommu/blob/main/iommu_ref_model/libiommu/src/iommu_ats.c#L324), only "Last Request in PRG" field set to 1 is checked and  "Stop Marker" consideration is missing there. I guess this is a bug and please help to check.

**Comment by ved-rivos** [comment]
Thanks. That was missed and updated in PR #338
