### ISSUE TITLE
update doc build workflow to latest from docs-spec-template

### ISSUE THREAD

**Issue by kbroch-rivosinc** [riscv-non-isa/riscv-iommu#340]
I'll put in a PR for this: 

* [x] update Makefile: src/build dir, HTML output
* [x] update docs-resources to latest
* [x] incorporate global adoc attributes from docs-resources
* [x] update adoc attributes in spec where needed
* [x] update GitHub action build flow where needed (src dir)
* [x] mv spec adoc files to src dir
* [x] add pre-commit
* [x] update README.adoc to incorporate all these changes

/cc @ved-rivos

**Comment by ved-rivos** [comment]
Thanks @kbroch-rivosinc
