### ISSUE TITLE
How is the requester ID assigned in an invalid request TLP packet?

### ISSUE THREAD

**Issue by dongxieDD** [riscv-non-isa/riscv-iommu#356]
In the invalid TLP packet, the device ID and requester ID are sent to the RC by the IOMMU. The device ID can be determined by the RID, so how should the requester ID be assigned?
![invld_req](https://github.com/riscv-non-isa/riscv-iommu/assets/80891627/0bd3550e-7fc1-44b0-b3e2-12abbcb0466f)
![invld_req1](https://github.com/riscv-non-isa/riscv-iommu/assets/80891627/40af5e6f-628b-4181-b86c-f432fcb8b66f)

**Comment by ved-rivos** [comment]
It's the host's requester ID.

**Comment by dongxieDD** [comment]
Thank you very much for your reply.

**Comment by 18772820305** [comment]
How to understand the host's request ID?

**Comment by ved-rivos** [comment]
It is usually the requester ID of the PCIe root port to which the the device is connected either directly or though switches. The configuration of the PCIe root complex is typically done by system firmware and OS that executes on the host as part of boot. This includes assigning the bus number for the PCIe root ports and the bus numbers for the secondary and subordinate buses. See example of PCI-PCI bridge configuration [here](http://www.science.unitn.it/~fiorella/guidelinux/tlk/node76.html#SECTION00862100000000000000) and [here](https://codywu2010.wordpress.com/2015/11/29/how-modern-multi-processor-multi-root-complex-system-assigns-pci-bus-number/).
