### ISSUE TITLE
iommu_translate_iova function may return the incorrect rsp_msg->trsp.is_msi when IOATC_HIT

### ISSUE THREAD

**Issue by francis4096** [riscv-non-isa/riscv-iommu#357]
Hi, 

https://github.com/riscv-non-isa/riscv-iommu/blob/dc44293bf52c6b6140c7253ffc8b87165fb13bc2/iommu_ref_model/libiommu/src/iommu_translate.c#L283C5-L283C51

When IOATC_HIT, the "is_msi" is not initialized.  but line 365 return it to  rsp_msg->trsp.is_msi.

**Comment by ved-rivos** [comment]
Thanks for reporting this. The ATC should cache `is_msi` unless `is_mrif` is also 1. Updated in #358
