### ISSUE TITLE
Question about capabilities access valid check when 32Byte read with offset equals 4 

### ISSUE THREAD

**Issue by viktoryou** [riscv-non-isa/riscv-iommu#364]
From the location of the [code](https://github.com/riscv-non-isa/riscv-iommu/blob/main/iommu_ref_model/libiommu/src/iommu_reg.c#L918),  I think `g_offset_to_size[CAPABILITIES_OFFSET + 4] = 8;` is missing. Please help to check.

**Comment by ved-rivos** [comment]
Did you mean `g_offset_to_size[FCTRL_OFFSET+4] = 4;` ? The field designated for custom use?

**Comment by ved-rivos** [comment]
never mind. Yes, that was missing and updated in #365
