### ISSUE TITLE
Question about cqen flag in detecting the state of command queue

### ISSUE THREAD

**Issue by viktoryou** [riscv-non-isa/riscv-iommu#368]
In the [code](https://github.com/riscv-non-isa/riscv-iommu/blob/main/iommu_ref_model/libiommu/src/iommu_command_queue.c#L52) of the model, cqcsr.cqen is not used in checking the state of command queue. Is that correct?

From the spec，
> When cqen is changed from 1 to 0, the command queue may stay active (with busy asserted) until the commands already fetched from the command-queue are being processed and/or there are outstanding implicit loads from the command-queue. When the command-queue turns off the cqon bit reads 0.

Should the fetch of new commands stop since cqen is changed from 1 to 0, or the fetch would be always active until the command queue becomes empty(seems like the behavior of the model)?

**Comment by ved-rivos** [comment]
The model was however missing the case where there might be a `IOFENCE` pending and the `cqon` clearing should be delayed. This is updated in #370 .
