### ISSUE TITLE
Question about updating reserved encoding in iohpmevt.eventid in the model 

### ISSUE THREAD

**Issue by viktoryou** [riscv-non-isa/riscv-iommu#375]
From the Table.17 in the spec, eventID value that greater than 8 is reserved. Since the field eventID in iohpmevt1-31 register is WARL, the illegal value from 9 to 16383 should be invisible. However I found that it is not guaranteed in the model and I guess it does not strictly follow with the spec.

**Comment by ved-rivos** [comment]
The range of eventIDs that the model supports is configured using the `eventID_mask` input to the `reset_iommu` function. However it's current definition as a mask currently needs the legal encoding to a power of 2. Its better to model it as a limit. Update in #376
