### ISSUE TITLE
Need to report Instruction Address Misaligned?

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#38]
In Section 3.2, "Fault/Event-Queue (FQ)", Table 7, the cause number 0, Instruction address misaligned, should probably never be reported.  (When would it be?)

**Comment by ved-rivos** [comment]
That is right. It will never be reported for instruction fetches. We should drop it from the table.

**Comment by ved-rivos** [comment]
Pull request for addressing issue
https://github.com/riscv-non-isa/riscv-iommu/pull/42

**Comment by ved-rivos** [comment]
Approved by IOMMU TG - 9/22/22
