### ISSUE TITLE
Question about gpasize in iotval2 when s1 bare and gpa over 56bit 

### ISSUE THREAD

**Issue by Orion3-e** [riscv-non-isa/riscv-iommu#385]
According to the spec 
![Snipaste_2024-07-25_11-41-46](https://github.com/user-attachments/assets/6bec3a0b-d66d-414a-8973-a321646097ac)
seems the iotval2 should save the whole gpa high part value [63:2],  even the gpa is over maxgpa , 
but in the c model , seems gpa dont save the value above 56bit when  S1 bare (va=gpa),  depending on page_sz .
![image](https://github.com/user-attachments/assets/202031fa-a40e-4373-93a4-f37851b53f21)
![image](https://github.com/user-attachments/assets/9bc85284-071b-4793-a670-5eb61b3b126f)
so , should the iotval2 save the upper_bits in this situation? thanks

**Comment by ved-rivos** [comment]
Do you have a test input that you can add to show what you mean? What was your input va and what do you see saved in iotval2 for that input?

**Comment by Orion3-e** [comment]
![image](https://github.com/user-attachments/assets/fccbbbea-0d87-41e8-a58f-4eaf220fc73d)
this is the req we send : iova = fffffff54d1ee2bc 
![image](https://github.com/user-attachments/assets/bbd98f15-dd99-44bc-a3ac-5ae8b9f1c43b)
this is the result covert from the rivos model 
![image](https://github.com/user-attachments/assets/1e33c872-127b-4aff-89b6-2e3b962ed67d)
this is the two stage function handles gpa for this req , the page_sz screenshoted in my last comment shows it is not 64 , causing the gpa high part [63:57] discarded
in this situation , dc.pdtv=1 && vsatp mode=bare so s1 bare va =gpa , so i think the iotval2 should save fffffff54d1ee2bc ,not the fffff54d1ee2bc in the temp fault q result rivos , seems bit [63:57] of iotval2 is discarded by two stage translation. Thanks

**Comment by ved-rivos** [comment]
The issue is that the pte->PPN is 44 bit wide. I have fixed this in #390 
Please also send me a direct message.

**Comment by Orion3-e** [comment]
Now the iotval2 check of that req pass,  thanks

**Comment by zetalog** [comment]
I have different opinion of the saved iotval/iotval2, probably you guys should take a look over it:
https://github.com/riscv-non-isa/riscv-iommu/issues/391
