### ISSUE TITLE
Missing condition to set CXL_IO within ATS translation response in the model

### ISSUE THREAD

**Issue by viktoryou** [riscv-non-isa/riscv-iommu#386]
From the spec,
> When a Success response is generated for an ATS translation request, the setting of the Priv, N, CXL.io, Global, and AMA fields is as follows:
...
If requesting device is a CXL type 1 or type 2 device
> * If the address is determined to be a MSI then the CXL.io bit is set to 1.
> * **Else if T2GPA is 1 in the device context then the CXL.io bit is set to 1**.
...

The behavior of the [model](https://github.com/riscv-non-isa/riscv-iommu/blob/main/iommu_ref_model/libiommu/src/iommu_translate.c#L452)  doesn't take the case where T2GPA is 1 into consideration. Please help to check.

**Comment by ved-rivos** [comment]
That was missing. Fixed in #389
