### ISSUE TITLE
ref model  iosatp_sv32 value is 1 ,but spec value is 8

### ISSUE THREAD

**Issue by xinyuwang-starfive** [riscv-non-isa/riscv-iommu#396]
i found the ref model iosatp_sv32 value is not same as spec value. does it right?
![image](https://github.com/user-attachments/assets/f730a395-55da-4f2a-a3d2-73843d9f25fc)
![image](https://github.com/user-attachments/assets/6a815fe6-e74a-4e98-9910-1a94e123fba7)

**Comment by ved-rivos** [comment]
Thanks for reporting this. Its fixed by #397
