### ISSUE TITLE
About situation in which IOMMU behavior is UNSPECIFIED in Debug support.

### ISSUE THREAD

**Issue by zhuotianshu** [riscv-non-isa/riscv-iommu#399]
In Chapter 4. Debug support:

> The IOMMU behavior is UNSPECIFIED if:
> • The tr_req_iova or tr_req_ctl are modified when the Go/Busy bit is 1.
> • IOMMU configurations such as ddtp.iommu_mode, etc. are modified.

Does the situation 2 holds only when the Go/Busy bit is 1?

**Comment by ved-rivos** [comment]
> Does the situation 2 holds only when the Go/Busy bit is 1?

Yes.

**Comment by zhuotianshu** [comment]
OK, thanks for your reply.
