### ISSUE TITLE
Maybe some typos.

### ISSUE THREAD

**Issue by zhuotianshu** [riscv-non-isa/riscv-iommu#400]
In 5.5. Device-directory-table pointer (ddtp):

> When an IOMMU is transitioned to **Bare of Off state**, the IOMMU may retain information cached from in-memory data structures such as page tables, DDT, PDT, etc. Software must use suitable invalidation commands to invalidate cached entries.

Does this means "Bare or Off state"?

And a very little question about a sentence in 3.2. Fault/Event-Queue (FQ):

> If the TTYP is a transaction with an IOVA then its reported in iotval.

If the meaning here is that the IOVA will be reported in iotval, then maybe here it should be "then it's reported in iotval."?

**Comment by ved-rivos** [comment]
> Does this means "Bare or Off state"?

Yes.

>  then maybe here it should be "then it's reported in iotval."?

Yes
