### ISSUE TITLE
Why the msi_addr_mask.mask and msi_addr_pattern.pattern are 52bits?

### ISSUE THREAD

**Issue by zhuotianshu** [riscv-non-isa/riscv-iommu#403]
Since the formula to decide whether a GPA is belong to MSI region is `(A >> 12) & ~msi_addr_mask = (msi_addr_pattern & ~msi_addr_mask)`, this means that` (A >> 12)` is bitwise & with a 64bits value which has bits63:52 reserved 0 but  bits51:0 can be set to one. Since a GPA can be 59bits at most, `GPA >> 12` can be 47 bits at most. It seems that writeable bits 51:47 should never be set. And if set, what should be the value of bits 51:47 of `GPA >> 12`. Should GPA be 0-extended?

**Comment by ved-rivos** [comment]
The GPA is required to be a valid GPA i.e. it cannot be wider than the widest GPA supported by the current iohgatp.MODE else it leads to a guest page fault. Thus bits 63:59 of a GPA must be 0. We could have reserved a few bits of the mask/pattern but chose not to.

**Comment by zhuotianshu** [comment]
OK, thanks for replying.
