### ISSUE TITLE
Scenario Issues Regarding SADE and GADE.

### ISSUE THREAD

**Issue by Taurins-peng** [riscv-non-isa/riscv-iommu#407]
Hi, I have a question regarding SADE and GADE. The following sentence indicates that a guest page fault occurs in this scenario.
![image](https://github.com/user-attachments/assets/daa090c3-b892-4091-926c-dc04bd1d4326)
The current case scenario is: SADE and GADE are 0, and the access type is write. The GPTE configuration is as follows:
![image](https://github.com/user-attachments/assets/2cddd321-04bb-48cd-b153-71e86f98ea0f)
I expect a guest page fault to occur, but the model changes the write to 0 when SADE is 0, making line 307 valid and proceeding to step_8 without reporting a guest page fault.
![Uploading Snipaste_2024-08-23_19-17-21.png…]()
![image](https://github.com/user-attachments/assets/bc39c663-d85a-4776-a15f-247413ab1792)
Could you explain this?

**Comment by Taurins-peng** [comment]
![image](https://github.com/user-attachments/assets/a14f5f5c-5224-4d32-95bf-103914c0c5b8)

**Comment by ved-rivos** [comment]
When SADE is 0 then the IOMMU does not do any A/D updates in VS-stage PTEs so VS-stage PTE accesses are always reads. Since there are no stores done to VS-stage PTEs there is no need for write permission checks for the G-stage PTEs that provide address translation to those VS-stage PTEs.

**Comment by Taurins-peng** [comment]
Thank you for the explanation.
