### ISSUE TITLE
IOTINVAL.VMA

### ISSUE THREAD

**Issue by asdvvcc123** [riscv-non-isa/riscv-iommu#416]
HI, sir: 

I find some problems  in this test too ; 

1,  
![image](https://github.com/user-attachments/assets/a3f47ee8-c6e7-48a9-8475-5e26042763bb)

2,   i think the second picture not same with the spec  ; here want to inv the G entry, i think it can't work if as the spec description ;
![image](https://github.com/user-attachments/assets/3c419b47-6741-41d4-96b0-10d69cbd6fca)
![image](https://github.com/user-attachments/assets/fcc2ad2e-11ed-4363-8470-55e1ceec385a)

thanks!!

**Comment by ved-rivos** [comment]
Thanks for reporting. Fixed in #417

**Comment by asdvvcc123** [comment]
thanks!!
