### ISSUE TITLE
enable_disable_pq

### ISSUE THREAD

**Issue by asdvvcc123** [riscv-non-isa/riscv-iommu#422]
hi，sir:
![image](https://github.com/user-attachments/assets/77430236-04db-4846-97dd-498d797a45b9)
this parameter not pass inside ; 

and here  has a place don't understand ; 
in here just a test for when busy can't disable ,right ?because the test in the enable process, so confuse  me here ; 
![image](https://github.com/user-attachments/assets/d36e35e6-5230-4433-ab3d-d4e2221ac195)

thanks a lot

**Comment by ved-rivos** [comment]
> this parameter not pass inside 

Yes, there was a bit of hard-coding. This is fixed by #423 

> in here just a test for when busy can't disable ,right ?

Yes. That test should have been in test app instead of in the utility function. This is fixed in #424 

Thanks for reporting.
