### ISSUE TITLE
implicit access is a read or a write

### ISSUE THREAD

**Issue by Taurins-peng** [riscv-non-isa/riscv-iommu#427]
Hi Sir, how can I distinguish whether the implicit access is a read or a write? Does this relate to the read or write configuration in my case?
![image](https://github.com/user-attachments/assets/e88a7331-225e-4e11-808e-8da3dba60b87)

**Comment by ved-rivos** [comment]
> how can I distinguish whether the implicit access is a read or a write?

A memory access to read or write PTEs are implicit accesses. As part of page table walk there is an implicit access to read the PTE from memory. Such reads are implicit read accesses. For a leaf PTE entry, when hardware A/D updates are supported and enabled, the IOMMU may do a write to the PTE to set the A and/or D bit. Such writes are implicit write accesses.

**Comment by ved-rivos** [comment]
Hope that helped. Please ask if there are further questions.
