### ISSUE TITLE
msi_address_translation

### ISSUE THREAD

**Issue by asdvvcc123** [riscv-non-isa/riscv-iommu#428]
hi，sir:
 1. 
in msi_address_translation , iotval2 is never be set ;   but in spec no place metion need to record gpa on msi transtion process or not  ; 
![image](https://github.com/user-attachments/assets/3d9fe6f2-1819-4722-8931-71d930a729c1)

2. here i think 52 is ok ; 
![image](https://github.com/user-attachments/assets/8cee00e9-b50f-4955-92ca-916579300263)

thanks!

**Comment by ved-rivos** [comment]
The spec states:
> If the CAUSE is a guest-page fault then bits 63:2 of the zero-extended guest-physical-address are reported in iotval2[63:2]. If bit 0 of iotval2 is 1, then the guest-page-fault was caused by an implicit memory access for first-stage address translation. If bit 0 of iotval2 is 1, and the implicit access was a write then bit 1 of iotval2 is set to 1 else it is set to 0.

iotval2 is  not reported for any other cause code. 

> here i think 52 is ok 

Yes. 52 would suffice since the data and mask are pre-shifted by 12 bits but this code is not wrong as the high order 12 bits in mask will be always 0.

**Comment by asdvvcc123** [comment]
thanks,get it
