### ISSUE TITLE
Duplicate paragraph was found in v1.01 spec

### ISSUE THREAD

**Issue by viktoryou** [riscv-non-isa/riscv-iommu#435]
In the latest spec, the added clarification from "Translations cached, if any, in Bare mode do not require invalidation." is duplicately pushed. See the [content](https://github.com/riscv-non-isa/riscv-iommu/blob/main/src/iommu_in_memory_queues.adoc?plain=1#L292-L298). It would be better if it gets clean.

**Comment by ved-rivos** [comment]
Thanks for spotting that. Will take care of it in next revision.

**Comment by ved-rivos** [comment]
PR #441 created to address.
