### ISSUE TITLE
DVM

### ISSUE THREAD

**Issue by yanhe234** [riscv-non-isa/riscv-iommu#436]
Under the ARM architecture, SMMU supports DVM operations for failed PTE operations in addition to commands. Currently, there is no definition similar to DVM under the RV architecture. What is the reason for this? Looking forward to your answer

**Comment by yanhe234** [comment]
Hello,sir. I understand that if we support something like DVM, would it have a significant impact on the entire ecosystem? And do you think this performance improvement is necessary?

**Comment by ved-rivos** [comment]
Whether it is a performance improvement compared to batched/deferred TLB invalidations using IPIs is uncertain. DVM type mechanism has however causes significant scaling and performance interference. For some background on this topic see:
https://lore.kernel.org/lkml/20230518065934.12877-1-yangyicong@huawei.com/
https://lore.kernel.org/all/20230717131004.12662-5-yangyicong@huawei.com/T/#u 
https://www.youtube.com/watch?v=jyohnitbXSk
Please do share any data/studies you have done in this space.
