### ISSUE TITLE
PV

### ISSUE THREAD

**Issue by yanhe234** [riscv-non-isa/riscv-iommu#437]
Is the PV field missing from the command IODIR.INVAL-PDT? I noticed that the PV field was introduced in section 6.3.1, but I did not see it in the command invalidation command

**Comment by ved-rivos** [comment]
You may be reading version 1.0.0 of the spec. Please read [version 1.0.1](https://github.com/riscv-non-isa/riscv-iommu/releases/tag/v1.0.1).

**Comment by yanhe234** [comment]
Very clear, thank you
