### ISSUE TITLE
when bare no need to check  PAS ?

### ISSUE THREAD

**Issue by asdvvcc123** [riscv-non-isa/riscv-iommu#442]
hi  ,sir :

in the tran function ,  when bare ,  jump to step 8  ,but in step 8 ,no code to check PAS;     

![image](https://github.com/user-attachments/assets/b6af4db5-8640-421e-bfc6-ac11ab932776)
![image](https://github.com/user-attachments/assets/521f57fd-fd5c-467d-aa07-07b53ad19788)

thanks!

**Comment by ved-rivos** [comment]
> in the tran function , when bare , jump to step 8 ,but in step 8 ,no code to check PAS;

The physical address that is the result of an address translation is provided to the IO bridge and further checking of validity of that PA is done by downstream components such as the PMA and PMP checkers.

**Comment by asdvvcc123** [comment]
![image](https://github.com/user-attachments/assets/a5781a59-aefe-49f3-9cc4-ce7d192d5e1e)
Hi,Sir: 
 i mean this parameter .    the final PA  no need to  limit by  this  parameter when bare ?   

thanks!

**Comment by ved-rivos** [comment]
> i mean this parameter . the final PA no need to limit by this parameter when bare ?

This parameter determines what the IOMMU itself can address. It does not affect the final PA (even when IOMMU is not in Bare mode).

**Comment by asdvvcc123** [comment]
ok  ,understand , thank !
