### ISSUE TITLE
Does IOMMU need to check the ddtp.iommu_mode of inbound invalid completion?

### ISSUE THREAD

**Issue by dongxieDD** [riscv-non-isa/riscv-iommu#443]

**Comment by dongxieDD** [comment]
Hello, I have an additional question. When g_reg_file.ddtp.iommu_mode is set to off or bare, how should the IOMMU handle receiving invalid completion messages?

**Comment by ved-rivos** [comment]
The iommu should handle invalidation completions normally even when it is in off or bare mode.

**Comment by ved-rivos** [comment]
No. It should not lead to a fault .

**Comment by dongxieDD** [comment]
Thank you for your reply.

**Comment by 18772820305** [comment]
When the iommu_mode switches to off, is it possible for there to be inflight transactions within the IOMMU?

**Comment by ved-rivos** [comment]
> When the iommu_mode switches to off, is it possible for there to be inflight transactions within the IOMMU?

When the `iommu_mode` field is changed to `Off`, there may be in-flight transactions in the IOMMU. The IOMMU however guarantees that in-flight transactions, observed at the time of the write to this field, will either be processed using the configurations applicable to the old value of the `iommu_mode` field or be aborted. See section 6.5

**Comment by yanhe234** [comment]
What is the process of handling cmd queue when ddtp.mode==bare or off without distinguishing domains? In other words, the processing of commands does not require attention to ddtp.mode? I understand that it is not necessary.
ARM's SMMU distinguishes between secure and non secure domains, while RV currently distinguishes between four domains. I am not sure how the queue processing of cmd needs to focus on ddtp when considering four domains under RV?
I don't know if I described it clearly. Looking forward to your reply

**Comment by ved-rivos** [comment]
Could you explain what you mean by four domains?

**Comment by yanhe234** [comment]
![捕获1](https://github.com/user-attachments/assets/99153354-8bf6-49cd-918c-1c25798f71ba)
This is from the RISC-V Supervisor Domains Access Protection document，Sir

**Comment by ved-rivos** [comment]
While that picture depicts 4 domains, the supervisor domain architecture is not limited to 4 domains. The supervisor domains architecture supports instantiation of multiple supervisor domains. One or more of those supervisor domains may be IO capable and may have an IOMMU associated with them. When an IOMMU is associated with a supervisor domain, that supervisor domain has exclusive access to that IOMMU - including its command queues. For further details see:
https://github.com/riscv/riscv-smmtt/blob/main/chapter6.adoc

![image](https://github.com/user-attachments/assets/94645ba2-4796-4e11-81bd-457d86ab8a02)

**Comment by yanhe234** [comment]
> What is the process of handling cmd queue when ddtp.mode==bare or off without distinguishing domains? In other words, the processing of commands does not require attention to ddtp.mode? I understand that it is not necessary. 
So, sir, I need to confirm the first question with you. When ddtp. mode==off or bare, will there be any discarding behavior when handling cmd queues?

**Comment by ved-rivos** [comment]
> So, sir, I need to confirm the first question with you. When ddtp. mode==off or bare, will there be any discarding behavior when handling cmd queues?

No. There isnt.

**Comment by yanhe234** [comment]
many  thanks

**Comment by 18772820305** [comment]
Hi, sir, When IOMMU_mode is set to off, should ATS invalidation completion be rejected/aborted/dropped?

**Comment by ved-rivos** [comment]
> When IOMMU_mode is set to off, should ATS invalidation completion be rejected/aborted/dropped?

The `iommu_mode` does not have affect how ATS invalidation completions are handled. They are handled normally irrespective of the `iommu_mode`.
