### ISSUE TITLE
FQ CAUSE 272

### ISSUE THREAD

**Issue by asdvvcc123** [riscv-non-isa/riscv-iommu#445]
hi,sir:

![image](https://github.com/user-attachments/assets/c57fb196-2c55-467c-8ae8-e25f15bf8f86)
What does  CAUSE 272 mean?  here don't understand;

is it same as axi bresp  DECERR?
![image](https://github.com/user-attachments/assets/0bacf7a9-08eb-4170-aff8-b8410b0858fe)

thank

**Comment by ved-rivos** [comment]
Its not related to AXI. This error code is related to RAS capabilities in an IOMMU as discussed in section 8.4.

**Comment by asdvvcc123** [comment]
thank,understand ；
