### ISSUE TITLE
When iohgatp and iosatp is all in Bare mode, is the MSI translation should be execute regardless the iohgatp.mode ? 

### ISSUE THREAD

**Issue by baimengwei** [riscv-non-isa/riscv-iommu#446]
According to the c model, after translate iova to GPA by `two_stage_address_translation`, the GPA will be checked for whether this GPA is a MSI.

however, the iohgatp.mode is Bare, which might means this GPA is a PA.  Is this still need a MSI translation ?  translate this GPA to a MSI PA or using the iohgatp.mode to bypass the MSI translation, which is more reasonable ? 

https://github.com/riscv-non-isa/riscv-iommu/blob/main/iommu_ref_model/libiommu/src/iommu_translate.c#L291

**Comment by ved-rivos** [comment]
The section 3.3 specifies the process to translate an IOVA. In the step 17 of the process the IOVA is translated to a GPA using the two stage address translation process. Then the step 18 is invoked to translate the GPA using MSI page tables if MSI page tables are enabled. If MSI page tables are not enabled or the GPA is not determined to be the address of a virtual interrupt file then in step 19 the GPA is translated to a SPA. When `iohgatp.mode` is Bare, the translation in step 19 is an identity translation as GPA is same as SPA.

**Comment by baimengwei** [comment]
Thanks.
