### ISSUE TITLE
Why the condition PDTV="0" needs to be added for the iohgatp.mode check？

### ISSUE THREAD

**Issue by 18772820305** [riscv-non-isa/riscv-iommu#448]
//13. `DC.iohgatp.MODE` encoding is not a valid encoding as determined 
 ​    ​//    by <<IOHGATP_MODE_ENC>> 
 ​    ​if​ ( (​DC​->​tc​.​PDTV​ ​==​ ​0​) ​&&​ (​g_reg_file​.​fctl​.​gxl​ ​==​ ​0​) ​&& 
 ​         (​DC​->​iohgatp​.​MODE​ ​!=​ ​IOHGATP_Bare​) ​&& 
 ​         (​DC​->​iohgatp​.​MODE​ ​!=​ ​IOHGATP_Sv39x4​) ​&& 
 ​         (​DC​->​iohgatp​.​MODE​ ​!=​ ​IOHGATP_Sv48x4​) ​&& 
 ​         (​DC​->​iohgatp​.​MODE​ ​!=​ ​IOHGATP_Sv57x4​) ) { 
 ​        ​return​ ​1​; 
 ​    } 
 ​    ​if​ ( (​DC​->​tc​.​PDTV​ ​==​ ​0​) ​&&​ (​g_reg_file​.​fctl​.​gxl​ ​==​ ​1​) ​&& 
 ​         (​DC​->​iohgatp​.​MODE​ ​!=​ ​IOHGATP_Bare​) ​&& 
 ​         (​DC​->​iohgatp​.​MODE​ ​!=​ ​IOHGATP_Sv32x4​) ) { 
 ​        ​return​ ​1​; 
 ​    }

**Comment by ved-rivos** [comment]
Thanks for reporting this. The step 13 does not require qualification by `PDTV` and the code here has an error that is fixed in #449
