### ISSUE TITLE
fqcsr.on

### ISSUE THREAD

**Issue by asdvvcc123** [riscv-non-isa/riscv-iommu#450]
hi ,sir : 
![image](https://github.com/user-attachments/assets/8c6e71b4-80e8-4e29-8da9-7b90b43406e0)
when fqen turn to 0  , here need wait fqon ,  fqon  need to wait all the fq done  or just currently no write happen ?

thanks

**Comment by ved-rivos** [comment]
Need to ensure that all writes in progress are completed and no new writes
will be done to FQ

**Comment by asdvvcc123** [comment]
hi ,sir: 
 "all writes in progress"     here mean the write already in the bus  , right?    
" no new writes will be done to FQ"  mean wait FQ be empty ?

thank

**Comment by asdvvcc123** [comment]
thank!
