### ISSUE TITLE
Clarify what is in doubleword iotval2 of a fault-queue record

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#46]
In Section 3.2, "Fault/Event-Queue (`FQ`)", instead of
> the guest-physical-address right shifted by 2 is reported in `iotval2[63:2]`

I think it would be clearer to say that bits 63:2 of the guest physical address are reported in `iotval2[63:2]`.

**Comment by ved-rivos** [comment]
Will update to:
If the `CAUSE` is a guest-page fault then bits 63:2 of the zero-extended guest-physical-address are reported in `iotval2[63:2]`.

**Comment by ved-rivos** [comment]
Address with pull request #48
