### ISSUE TITLE
Register field types in glossary

### ISSUE THREAD

**Issue by dgptha** [riscv-non-isa/riscv-iommu#5]
The WARL and the WPRI register field types appear in the glossary, but the other types (RO, RW, RW1C) don't.
I would remove WARL and WPRI from the glossary, as those have their dedicated table (Chapter 4 Table 10 *Register and Register bit-field types*).
Otherwise the others (RO, RW, RW1C) should be added to the glossary.

**Comment by ved-rivos** [comment]
Agree. Added the other types to the glossary.

**Comment by ved-rivos** [comment]
Resolving this as completed.
