### ISSUE TITLE
Maximum width of GSCID and PSCID

### ISSUE THREAD

**Issue by ved-rivos** [riscv-non-isa/riscv-iommu#50]
The architecture presently requires support for 16 bit GSCID and 20 bit PSCID.
In smaller implementation it may be desirable to support a less wider GSCID and PSCID.

Proposed update to the text:
The number of implemented bits of GSCID width, termed GSCIDLEN,
must be 8 bits if the maximum supported device_id width is less than or 
equal to 8 bits; else it must be 16 bits.

When GSCIDLEN is 8 bits, Bits 15:8 of GSCID in fields of in-memory
data structures and in register fields must be set to 0 by software. If not set to 0
then the implementation may either ignore the bits 15:8 or use all or parts
it as GSCID.

The number of implemented bits of PSCID width, termed PSCIDLEN,
must be 20 bits if the supported process_id width is greater than 8-bits.
When the supported process_id width is less than or equal to 8-bits, the
PSCIDLEN must be the same as GSCIDLEN. 

When PSCIDLEN is not 20 bits, Bits 19:PSCIDLEN in fields of in-memory
data structures and in register field must be set to 0 by software.  If not set to 0
then the implementation may either ignore the bits 19:PSCIDLEN or use all or
 parts of it as PSCID.

**Comment by yanhe234** [comment]
The bit widths of GSCID and PSCID in the privileged document are 14 and 16, respectively. However, the IOMMU document specifies that the bit widths of the two are 16 and 20. Looking forward to your answer

**Comment by yanhe234** [comment]
I understand that the roles of VMID and AISD in privileged documents are the same as GSCID and PSCID, both of which are used to distinguish between virtual machines and address spaces. Are there any other considerations here? Can you provide a more detailed introduction? Thank you for your response,

**Comment by ved-rivos** [comment]
The key difference is that while ASID and VMID are hart local, GSCID and PSCID are global.
Please see this note from Priv. spec:
> If a hart employs an address-translation cache, that cache must appear to be private to that hart. In particular, the meaning of an ASID is local to a hart; software may choose to use the same ASID to refer to different address spaces on different harts.

> A future extension could redefine ASIDs to be global across the SEE, enabling such options as shared translation caches and hardware support for broadcast TLB shootdown. However, as OSes have evolved to significantly reduce the scope of TLB shootdowns using novel ASID-management techniques, we expect the local-ASID scheme to remain attractive for its simplicity and possibly better scalability

**Comment by yanhe234** [comment]
I have learned a lot from you, and I may need to reconsider some of your answers. If you have any questions, I will ask you again. I wish you good health and a happy family. Thank you very much
