### ISSUE TITLE
RV32 can configure ddtp with one 32-bit store

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#51]
In Section 5.5, "Device-directory-table pointer (`ddtp`)", this comment is no longer valid:
> In RV32, memory-mapped writes to `ddtp` modify only one 32-bit part of the register. The following sequence may be used to update the register using two 32-bit writes.
> - Write the low order 32-bits to update the `PPN`. In RV32, the `PPN` is upto 22-bits.
> - Write the high order 32-bits to update the `iommu_mode` if required.

**Comment by ved-rivos** [comment]
PR #25 is queued to address this.
