### ISSUE TITLE
Consider renaming ctrl to be ctl

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#54]
Existing RISC-V conventions are supposed to be that register names use the abbreviation `ctl` for *control*.  Accordingly, please consider renaming `fctrl` to `fctl`, `tr_req_ctrl` to `tr_req_ctl`, and `msi_vec_ctrl_*` to `msi_vec_ctl_*`.

(No, this convention isn't written down anywhere right now as far as I know.  But it is the reason why the AIA has a CSR called `hvictl`.)

**Comment by ved-rivos** [comment]
Addressed by PR #56
