### ISSUE TITLE
WSI instead of WIS?

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#55]
Since we already have *MSI* for *message-signaled interrupt*, wouldn't it be more consistent to use *WSI* for *wire-signaled interrupt*, and not *WIS* for *wired-interrupt signaling*?

**Comment by ved-rivos** [comment]
Approved by IOMMU TG - 9/29/2022

**Comment by ved-rivos** [comment]
Addressed by PR #56
