### ISSUE TITLE
In address translation algorithm, many branches go to wrong step? 

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#58]
In Section 2.4, "Process to translate an IOVA", it looks to me like step 2 should conditionally go to step 21 instead of 19,  Same for step 8:  It should conditionally go to step 21 instead of 19.  I think step 9 is supposed to conditionally go to step 19 instead of 17.  There may be more of these errors.

**Comment by ved-rivos** [comment]
Embarrassing error introduced by the big merge. 
Addressed by #60
