### ISSUE TITLE
What G-stage page-table MODE is "Off"?

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#59]
In Section 2.1.4, "Device-context configuration checks", we have:
> 7. `DC.tc.T2GPA` is 1 and `DC.iohgatp.MODE` is `Off` or is `Bare`

What value of the MODE field means `Off`?

**Comment by ved-rivos** [comment]
It should not say is Off.

**Comment by ved-rivos** [comment]
Address by #60
