### ISSUE TITLE
Optional registers

### ISSUE THREAD

**Issue by dgptha** [riscv-non-isa/riscv-iommu#6]
Some of the registers are optional depending on the supported capabilities specified on the capabilities register of the IOMMU.
For example the performance monitoring registers.
However, this information doesn't appear clearly in the text and the behavior of those registers (probably WPRI) is not specified.
It could be already specified in the Section 4.1 *Register layout* Table 11, with an additional column specifying if the register is "Optional" with three values:
- N: the register is mandatory
- Y: the register is optional, if the capability is not supported the register is reserved (WPRI). The register can not be reused for an alternative 
- N/A: for reserved and custom offsets

**Comment by ved-rivos** [comment]
Agree. Will add a column with a reference to the capability that would make it optional.

**Comment by ved-rivos** [comment]
Resolving this as completed.
