### ISSUE TITLE
Minor issues found when reading specs document

### ISSUE THREAD

**Issue by malejo97** [riscv-non-isa/riscv-iommu#83]
A few minor issues found when reading the IOMMU specs document:

- Page 65: **icvec** register is specified as being 4-byte width in the register layout table, but it is 64-bit wide.
- Page 78: Bit order of reserved field in **fqcsr**: **15:10** instead of 10:15.
- Page 87: **icvec** register's description should be after translation request registers, to match the order/offsets specified in the table and avoid confusion (This way, the three translation request registers description would be in subsections 5.24, 5.25 and 5.26, respectively; and the **icvec** reg description would be in subsection 5.27).

**Comment by ved-rivos** [comment]
Thanks! PR #84 is created  to address these items.
