### ISSUE TITLE
cqt should be cqh

### ISSUE THREAD

**Issue by jhauser-us** [riscv-non-isa/riscv-iommu#91]
In Section 5.15, "Command-queue CSR (`cqcsr`)":
> When `cmd_ill` or `cqmf` is 1 in `cqcsr` the `cqt` references the command in the CQ that caused these error.

And then:
> When `cmd_to` is 1 `cqt` references the IOFENCE.C command that detected the timeout.

In both of these sentences, "`cqt`" should be "`cqh`".

**Comment by ved-rivos** [comment]
PR #96 created to address the issue.

**Comment by jhauser-us** [comment]
Accepted.
